name:                haskell-kitchen
version:             0.1.0.0
github:              "wayneseymour/haskell-kitchen"
license:             BSD3
author:              "Tre&#39; Seymour"
maintainer:          "tre.codez@gmail.com"
copyright:           "Copyright (c) 2020 Tre&#39; Seymour"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wayneseymour/haskell-kitchen#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-kitchen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-kitchen

tests:
  haskell-kitchen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-kitchen
